---
- name: Setup production-grade server
  hosts: all
  become: true
  vars:
    user_name: Sysadmin
    user_shell: /bin/bash
    sudoers_file: /etc/sudoers
    hostname: production-grade
    docker_logging_driver: "json-file"
    docker_storage_driver: "overlay2"

  tasks:
    - name: Create the user
      user:
        name: "{{ user_name }}"
        state: present
        shell: "{{ user_shell }}"

    - name: Add user to sudoers file
      lineinfile:
        path: "{{ sudoers_file }}"
        line: "{{ user_name }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'

    - name: Set the hostname
      hostname:
        name: "{{ hostname }}"

    - name: Install necessary packages
      apt:
        name:
          - curl
          - net-tools
          - vim
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Configure Docker logging driver
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "{{ docker_logging_driver }}",
            "storage-driver": "{{ docker_storage_driver }}"
          }
        owner: root
        group: root
        mode: '0644'
      notify: Restart Docker

    - name: Restart Docker service
      service:
        name: docker
        state: restarted

    - name: Tune the server for high network traffic workload
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        sysctl_set: yes
      with_items:
        - { name: 'net.core.netdev_max_backlog', value: '5000' }
        - { name: 'net.core.somaxconn', value: '1024' }
        - { name: 'net.ipv4.tcp_max_syn_backlog', value: '4096' }
        - { name: 'net.ipv4.tcp_syncookies', value: '1' }
        - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }

  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
